name: Update README with repo list

on:
  schedule:
    - cron: "0 0 * * *"   # har kuni UTC 00:00 da yangilanadi
  workflow_dispatch:       # qo'lda ham ishga tushirish mumkin

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate repo list (repos.md)
        id: gen
        uses: actions/github-script@v6
        with:
          script: |
            const repos = await github.paginate(github.rest.repos.listForUser, {
              username: context.repo.owner,
              type: 'owner',
              per_page: 100
            });

            const publicRepos = repos.filter(r => !r.private);

            const md = publicRepos
              .map(r => `- [${r.name}](${r.html_url})`)
              .join('\n') || '_(No public repositories yet)_';

            require('fs').writeFileSync('repos.md', md);
            return md;

      - name: Insert repo list into README
        run: python .github/scripts/update_readme.py

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update README repo list"
            git push
          fi
